# Generated by Django 4.2.5 on 2024-02-21 10:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_startdate', models.DateTimeField()),
                ('rental_enddate', models.DateTimeField()),
                ('totalcost', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RentalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=100)),
                ('rental_status', models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], default='Available', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=100)),
                ('reg_number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('damage_cost', models.PositiveIntegerField()),
                ('date_reported', models.DateField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.rentaltransactions')),
            ],
        ),
        migrations.AddField(
            model_name='rentaltransactions',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.rentalvehicle'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.DateField(auto_now_add=True)),
                ('paymentamount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('online', 'online')], default='cash', max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('failed', 'failed'), ('completed', 'completed')], default='pending', max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.rentaltransactions')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=300)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.rentaltransactions')),
            ],
        ),
    ]
