# Generated by Django 4.2.5 on 2024-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_vehiclepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalvehicle',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='usedvehicle',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
