# Generated by Django 5.0.2 on 2024-03-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0006_payment_customer_vehiclepurchase_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedvehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=50),
        ),
    ]
