# Generated by Django 5.0.2 on 2024-03-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0007_usedvehicle_vehicle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='damage_cost',
        ),
        migrations.AddField(
            model_name='report',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.customer'),
        ),
        migrations.AddField(
            model_name='report',
            name='damage_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ReportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('report_status', models.CharField(choices=[('No damage till now', 'No damage till now'), ('Damage req sent', 'Damage req sent'), ('Damage money pending', 'Damage money pending'), ('Damage solved', 'Damage solved')], default='No damage till now', max_length=50)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.report')),
            ],
        ),
    ]
