# Generated by Django 4.2.5 on 2024-03-14 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0009_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.rentaltransactions', unique=True),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.report', unique=True),
        ),
    ]
