# Generated by Django 4.2.5 on 2024-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0010_alter_report_transaction_alter_reportresponse_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportresponse',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
